name: meet
description: A one page portfolio.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.2
  responsive_framework: ^0.0.14
  flutter_icons: ^1.1.0
  smooth_page_indicator: ^0.2.0
  carousel_slider: ^3.0.0
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.9
  url_launcher_web: ^2.0.0
  mailto: ^2.0.0
  font_awesome_flutter: ^9.1.0
  animated_splash_screen: ^1.1.0
  flutter_native_splash: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Bold.ttf
        - asset: fonts/Quicksand-Light.ttf
        - asset: fonts/Quicksand-Medium.ttf
        - asset: fonts/Quicksand-Regular.ttf
        - asset: fonts/Quicksand-SemiBold.ttf
